package Protege.impl;

import Protege.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultIncident <br>
 * @version generated on Thu Nov 16 09:04:53 MST 2017 by danielmejia
 */
public class DefaultIncident extends WrappedIndividualImpl implements Incident {

    public DefaultIncident(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#contains
     */
     
    public Collection<? extends WrappedIndividual> getContains() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_CONTAINS,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasContains() {
	   return !getContains().isEmpty();
    }

    public void addContains(WrappedIndividual newContains) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_CONTAINS,
                                       newContains);
    }

    public void removeContains(WrappedIndividual oldContains) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_CONTAINS,
                                          oldContains);
    }


    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#has
     */
     
    public Collection<? extends WrappedIndividual> getHas() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHas() {
	   return !getHas().isEmpty();
    }

    public void addHas(WrappedIndividual newHas) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS,
                                       newHas);
    }

    public void removeHas(WrappedIndividual oldHas) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS,
                                          oldHas);
    }


    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#involves
     */
     
    public Collection<? extends Person> getInvolves() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_INVOLVES,
                                               DefaultPerson.class);
    }

    public boolean hasInvolves() {
	   return !getInvolves().isEmpty();
    }

    public void addInvolves(Person newInvolves) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_INVOLVES,
                                       newInvolves);
    }

    public void removeInvolves(Person oldInvolves) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_INVOLVES,
                                          oldInvolves);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#has1000DollarDamage
     */
     
    public Collection<? extends Integer> getHas1000DollarDamage() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS1000DOLLARDAMAGE, Integer.class);
    }

    public boolean hasHas1000DollarDamage() {
		return !getHas1000DollarDamage().isEmpty();
    }

    public void addHas1000DollarDamage(Integer newHas1000DollarDamage) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS1000DOLLARDAMAGE, newHas1000DollarDamage);
    }

    public void removeHas1000DollarDamage(Integer oldHas1000DollarDamage) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS1000DOLLARDAMAGE, oldHas1000DollarDamage);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCMVFlag
     */
     
    public Collection<? extends Integer> getHasCMVFlag() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCMVFLAG, Integer.class);
    }

    public boolean hasHasCMVFlag() {
		return !getHasCMVFlag().isEmpty();
    }

    public void addHasCMVFlag(Integer newHasCMVFlag) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCMVFLAG, newHasCMVFlag);
    }

    public void removeHasCMVFlag(Integer oldHasCMVFlag) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCMVFLAG, oldHasCMVFlag);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCity
     */
     
    public Collection<? extends String> getHasCity() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCITY, String.class);
    }

    public boolean hasHasCity() {
		return !getHasCity().isEmpty();
    }

    public void addHasCity(String newHasCity) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCITY, newHasCity);
    }

    public void removeHasCity(String oldHasCity) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCITY, oldHasCity);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCollisionType
     */
     
    public Collection<? extends Integer> getHasCollisionType() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOLLISIONTYPE, Integer.class);
    }

    public boolean hasHasCollisionType() {
		return !getHasCollisionType().isEmpty();
    }

    public void addHasCollisionType(Integer newHasCollisionType) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOLLISIONTYPE, newHasCollisionType);
    }

    public void removeHasCollisionType(Integer oldHasCollisionType) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOLLISIONTYPE, oldHasCollisionType);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasConstructionWorkerFlag
     */
     
    public Collection<? extends Integer> getHasConstructionWorkerFlag() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONSTRUCTIONWORKERFLAG, Integer.class);
    }

    public boolean hasHasConstructionWorkerFlag() {
		return !getHasConstructionWorkerFlag().isEmpty();
    }

    public void addHasConstructionWorkerFlag(Integer newHasConstructionWorkerFlag) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONSTRUCTIONWORKERFLAG, newHasConstructionWorkerFlag);
    }

    public void removeHasConstructionWorkerFlag(Integer oldHasConstructionWorkerFlag) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONSTRUCTIONWORKERFLAG, oldHasConstructionWorkerFlag);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasConstructionZoneFlag
     */
     
    public Collection<? extends Integer> getHasConstructionZoneFlag() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONSTRUCTIONZONEFLAG, Integer.class);
    }

    public boolean hasHasConstructionZoneFlag() {
		return !getHasConstructionZoneFlag().isEmpty();
    }

    public void addHasConstructionZoneFlag(Integer newHasConstructionZoneFlag) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONSTRUCTIONZONEFLAG, newHasConstructionZoneFlag);
    }

    public void removeHasConstructionZoneFlag(Integer oldHasConstructionZoneFlag) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONSTRUCTIONZONEFLAG, oldHasConstructionZoneFlag);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCounty
     */
     
    public Collection<? extends String> getHasCounty() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOUNTY, String.class);
    }

    public boolean hasHasCounty() {
		return !getHasCounty().isEmpty();
    }

    public void addHasCounty(String newHasCounty) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOUNTY, newHasCounty);
    }

    public void removeHasCounty(String oldHasCounty) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOUNTY, oldHasCounty);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashID
     */
     
    public Collection<? extends Integer> getHasCrashID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHID, Integer.class);
    }

    public boolean hasHasCrashID() {
		return !getHasCrashID().isEmpty();
    }

    public void addHasCrashID(Integer newHasCrashID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHID, newHasCrashID);
    }

    public void removeHasCrashID(Integer oldHasCrashID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHID, oldHasCrashID);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashSeverity
     */
     
    public Collection<? extends Integer> getHasCrashSeverity() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHSEVERITY, Integer.class);
    }

    public boolean hasHasCrashSeverity() {
		return !getHasCrashSeverity().isEmpty();
    }

    public void addHasCrashSeverity(Integer newHasCrashSeverity) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHSEVERITY, newHasCrashSeverity);
    }

    public void removeHasCrashSeverity(Integer oldHasCrashSeverity) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHSEVERITY, oldHasCrashSeverity);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashTime
     */
     
    public Collection<? extends Integer> getHasCrashTime() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHTIME, Integer.class);
    }

    public boolean hasHasCrashTime() {
		return !getHasCrashTime().isEmpty();
    }

    public void addHasCrashTime(Integer newHasCrashTime) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHTIME, newHasCrashTime);
    }

    public void removeHasCrashTime(Integer oldHasCrashTime) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHTIME, oldHasCrashTime);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashYear
     */
     
    public Collection<? extends Integer> getHasCrashYear() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHYEAR, Integer.class);
    }

    public boolean hasHasCrashYear() {
		return !getHasCrashYear().isEmpty();
    }

    public void addHasCrashYear(Integer newHasCrashYear) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHYEAR, newHasCrashYear);
    }

    public void removeHasCrashYear(Integer oldHasCrashYear) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCRASHYEAR, oldHasCrashYear);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasDayOfWeek
     */
     
    public Collection<? extends Integer> getHasDayOfWeek() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDAYOFWEEK, Integer.class);
    }

    public boolean hasHasDayOfWeek() {
		return !getHasDayOfWeek().isEmpty();
    }

    public void addHasDayOfWeek(Integer newHasDayOfWeek) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDAYOFWEEK, newHasDayOfWeek);
    }

    public void removeHasDayOfWeek(Integer oldHasDayOfWeek) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDAYOFWEEK, oldHasDayOfWeek);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasDeathCount
     */
     
    public Collection<? extends Integer> getHasDeathCount() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDEATHCOUNT, Integer.class);
    }

    public boolean hasHasDeathCount() {
		return !getHasDeathCount().isEmpty();
    }

    public void addHasDeathCount(Integer newHasDeathCount) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDEATHCOUNT, newHasDeathCount);
    }

    public void removeHasDeathCount(Integer oldHasDeathCount) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASDEATHCOUNT, oldHasDeathCount);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasHWNumber
     */
     
    public Collection<? extends Integer> getHasHWNumber() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHWNUMBER, Integer.class);
    }

    public boolean hasHasHWNumber() {
		return !getHasHWNumber().isEmpty();
    }

    public void addHasHWNumber(Integer newHasHWNumber) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHWNUMBER, newHasHWNumber);
    }

    public void removeHasHWNumber(Integer oldHasHWNumber) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHWNUMBER, oldHasHWNumber);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasHWSystem
     */
     
    public Collection<? extends Integer> getHasHWSystem() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHWSYSTEM, Integer.class);
    }

    public boolean hasHasHWSystem() {
		return !getHasHWSystem().isEmpty();
    }

    public void addHasHWSystem(Integer newHasHWSystem) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHWSYSTEM, newHasHWSystem);
    }

    public void removeHasHWSystem(Integer oldHasHWSystem) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHWSYSTEM, oldHasHWSystem);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasIntersectionFlag
     */
     
    public Collection<? extends Integer> getHasIntersectionFlag() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASINTERSECTIONFLAG, Integer.class);
    }

    public boolean hasHasIntersectionFlag() {
		return !getHasIntersectionFlag().isEmpty();
    }

    public void addHasIntersectionFlag(Integer newHasIntersectionFlag) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASINTERSECTIONFLAG, newHasIntersectionFlag);
    }

    public void removeHasIntersectionFlag(Integer oldHasIntersectionFlag) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASINTERSECTIONFLAG, oldHasIntersectionFlag);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasLatitude
     */
     
    public Collection<? extends Object> getHasLatitude() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLATITUDE, Object.class);
    }

    public boolean hasHasLatitude() {
		return !getHasLatitude().isEmpty();
    }

    public void addHasLatitude(Object newHasLatitude) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLATITUDE, newHasLatitude);
    }

    public void removeHasLatitude(Object oldHasLatitude) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLATITUDE, oldHasLatitude);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasLightCondition
     */
     
    public Collection<? extends Integer> getHasLightCondition() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLIGHTCONDITION, Integer.class);
    }

    public boolean hasHasLightCondition() {
		return !getHasLightCondition().isEmpty();
    }

    public void addHasLightCondition(Integer newHasLightCondition) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLIGHTCONDITION, newHasLightCondition);
    }

    public void removeHasLightCondition(Integer oldHasLightCondition) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLIGHTCONDITION, oldHasLightCondition);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasLongitude
     */
     
    public Collection<? extends Object> getHasLongitude() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLONGITUDE, Object.class);
    }

    public boolean hasHasLongitude() {
		return !getHasLongitude().isEmpty();
    }

    public void addHasLongitude(Object newHasLongitude) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLONGITUDE, newHasLongitude);
    }

    public void removeHasLongitude(Object oldHasLongitude) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLONGITUDE, oldHasLongitude);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasRRFlag
     */
     
    public Collection<? extends Integer> getHasRRFlag() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASRRFLAG, Integer.class);
    }

    public boolean hasHasRRFlag() {
		return !getHasRRFlag().isEmpty();
    }

    public void addHasRRFlag(Integer newHasRRFlag) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASRRFLAG, newHasRRFlag);
    }

    public void removeHasRRFlag(Integer oldHasRRFlag) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASRRFLAG, oldHasRRFlag);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSchoolBusFlag
     */
     
    public Collection<? extends Integer> getHasSchoolBusFlag() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSCHOOLBUSFLAG, Integer.class);
    }

    public boolean hasHasSchoolBusFlag() {
		return !getHasSchoolBusFlag().isEmpty();
    }

    public void addHasSchoolBusFlag(Integer newHasSchoolBusFlag) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSCHOOLBUSFLAG, newHasSchoolBusFlag);
    }

    public void removeHasSchoolBusFlag(Integer oldHasSchoolBusFlag) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSCHOOLBUSFLAG, oldHasSchoolBusFlag);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSchoolZoneFlag
     */
     
    public Collection<? extends Integer> getHasSchoolZoneFlag() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSCHOOLZONEFLAG, Integer.class);
    }

    public boolean hasHasSchoolZoneFlag() {
		return !getHasSchoolZoneFlag().isEmpty();
    }

    public void addHasSchoolZoneFlag(Integer newHasSchoolZoneFlag) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSCHOOLZONEFLAG, newHasSchoolZoneFlag);
    }

    public void removeHasSchoolZoneFlag(Integer oldHasSchoolZoneFlag) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSCHOOLZONEFLAG, oldHasSchoolZoneFlag);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSpeedLimit
     */
     
    public Collection<? extends Integer> getHasSpeedLimit() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSPEEDLIMIT, Integer.class);
    }

    public boolean hasHasSpeedLimit() {
		return !getHasSpeedLimit().isEmpty();
    }

    public void addHasSpeedLimit(Integer newHasSpeedLimit) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSPEEDLIMIT, newHasSpeedLimit);
    }

    public void removeHasSpeedLimit(Integer oldHasSpeedLimit) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSPEEDLIMIT, oldHasSpeedLimit);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSurfaceCondition
     */
     
    public Collection<? extends Integer> getHasSurfaceCondition() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSURFACECONDITION, Integer.class);
    }

    public boolean hasHasSurfaceCondition() {
		return !getHasSurfaceCondition().isEmpty();
    }

    public void addHasSurfaceCondition(Integer newHasSurfaceCondition) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSURFACECONDITION, newHasSurfaceCondition);
    }

    public void removeHasSurfaceCondition(Integer oldHasSurfaceCondition) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSURFACECONDITION, oldHasSurfaceCondition);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasWeather
     */
     
    public Collection<? extends Integer> getHasWeather() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASWEATHER, Integer.class);
    }

    public boolean hasHasWeather() {
		return !getHasWeather().isEmpty();
    }

    public void addHasWeather(Integer newHasWeather) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASWEATHER, newHasWeather);
    }

    public void removeHasWeather(Integer oldHasWeather) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASWEATHER, oldHasWeather);
    }


}
