package Protege.impl;

import Protege.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTrafficVolume <br>
 * @version generated on Mon Mar 06 21:12:32 MST 2017 by danielmejia
 */
public class DefaultTrafficVolume extends WrappedIndividualImpl implements TrafficVolume {

    public DefaultTrafficVolume(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#Calculates
     */
     
    public Collection<? extends WrappedIndividual> getCalculates() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_CALCULATES,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasCalculates() {
	   return !getCalculates().isEmpty();
    }

    public void addCalculates(WrappedIndividual newCalculates) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_CALCULATES,
                                       newCalculates);
    }

    public void removeCalculates(WrappedIndividual oldCalculates) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_CALCULATES,
                                          oldCalculates);
    }


    /* ***************************************************
     * Object Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#affects
     */
     
    public Collection<? extends WrappedIndividual> getAffects() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AFFECTS,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasAffects() {
	   return !getAffects().isEmpty();
    }

    public void addAffects(WrappedIndividual newAffects) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AFFECTS,
                                       newAffects);
    }

    public void removeAffects(WrappedIndividual oldAffects) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AFFECTS,
                                          oldAffects);
    }


    /* ***************************************************
     * Object Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#coversArea
     */
     
    public Collection<? extends GeographicalArea> getCoversArea() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_COVERSAREA,
                                               DefaultGeographicalArea.class);
    }

    public boolean hasCoversArea() {
	   return !getCoversArea().isEmpty();
    }

    public void addCoversArea(GeographicalArea newCoversArea) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_COVERSAREA,
                                       newCoversArea);
    }

    public void removeCoversArea(GeographicalArea oldCoversArea) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_COVERSAREA,
                                          oldCoversArea);
    }


    /* ***************************************************
     * Object Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#isIndicatorOf
     */
     
    public Collection<? extends WrappedIndividual> getIsIndicatorOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISINDICATOROF,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasIsIndicatorOf() {
	   return !getIsIndicatorOf().isEmpty();
    }

    public void addIsIndicatorOf(WrappedIndividual newIsIndicatorOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISINDICATOROF,
                                       newIsIndicatorOf);
    }

    public void removeIsIndicatorOf(WrappedIndividual oldIsIndicatorOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISINDICATOROF,
                                          oldIsIndicatorOf);
    }


    /* ***************************************************
     * Object Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#multiplyByLength
     */
     
    public Collection<? extends VehicleMilesTraveled> getMultiplyByLength() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_MULTIPLYBYLENGTH,
                                               DefaultVehicleMilesTraveled.class);
    }

    public boolean hasMultiplyByLength() {
	   return !getMultiplyByLength().isEmpty();
    }

    public void addMultiplyByLength(VehicleMilesTraveled newMultiplyByLength) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_MULTIPLYBYLENGTH,
                                       newMultiplyByLength);
    }

    public void removeMultiplyByLength(VehicleMilesTraveled oldMultiplyByLength) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_MULTIPLYBYLENGTH,
                                          oldMultiplyByLength);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasCommuterStressIndex.Value
     */
     
    public Collection<? extends Object> getHasCommuterStressIndex.Value() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOMMUTERSTRESSINDEX.VALUE, Object.class);
    }

    public boolean hasHasCommuterStressIndex.Value() {
		return !getHasCommuterStressIndex.Value().isEmpty();
    }

    public void addHasCommuterStressIndex.Value(Object newHasCommuterStressIndex.Value) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOMMUTERSTRESSINDEX.VALUE, newHasCommuterStressIndex.Value);
    }

    public void removeHasCommuterStressIndex.Value(Object oldHasCommuterStressIndex.Value) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOMMUTERSTRESSINDEX.VALUE, oldHasCommuterStressIndex.Value);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasCommuterStressIndex.id
     */
     
    public Collection<? extends Integer> getHasCommuterStressIndex.id() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOMMUTERSTRESSINDEX.ID, Integer.class);
    }

    public boolean hasHasCommuterStressIndex.id() {
		return !getHasCommuterStressIndex.id().isEmpty();
    }

    public void addHasCommuterStressIndex.id(Integer newHasCommuterStressIndex.id) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOMMUTERSTRESSINDEX.ID, newHasCommuterStressIndex.id);
    }

    public void removeHasCommuterStressIndex.id(Integer oldHasCommuterStressIndex.id) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCOMMUTERSTRESSINDEX.ID, oldHasCommuterStressIndex.id);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasCongestionCost.id
     */
     
    public Collection<? extends Integer> getHasCongestionCost.id() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONGESTIONCOST.ID, Integer.class);
    }

    public boolean hasHasCongestionCost.id() {
		return !getHasCongestionCost.id().isEmpty();
    }

    public void addHasCongestionCost.id(Integer newHasCongestionCost.id) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONGESTIONCOST.ID, newHasCongestionCost.id);
    }

    public void removeHasCongestionCost.id(Integer oldHasCongestionCost.id) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONGESTIONCOST.ID, oldHasCongestionCost.id);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasCongestionTime.id
     */
     
    public Collection<? extends Integer> getHasCongestionTime.id() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONGESTIONTIME.ID, Integer.class);
    }

    public boolean hasHasCongestionTime.id() {
		return !getHasCongestionTime.id().isEmpty();
    }

    public void addHasCongestionTime.id(Integer newHasCongestionTime.id) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONGESTIONTIME.ID, newHasCongestionTime.id);
    }

    public void removeHasCongestionTime.id(Integer oldHasCongestionTime.id) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASCONGESTIONTIME.ID, oldHasCongestionTime.id);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasFatalIncident.id
     */
     
    public Collection<? extends Integer> getHasFatalIncident.id() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASFATALINCIDENT.ID, Integer.class);
    }

    public boolean hasHasFatalIncident.id() {
		return !getHasFatalIncident.id().isEmpty();
    }

    public void addHasFatalIncident.id(Integer newHasFatalIncident.id) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASFATALINCIDENT.ID, newHasFatalIncident.id);
    }

    public void removeHasFatalIncident.id(Integer oldHasFatalIncident.id) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASFATALINCIDENT.ID, oldHasFatalIncident.id);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasGasEmission.id
     */
     
    public Collection<? extends Integer> getHasGasEmission.id() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASGASEMISSION.ID, Integer.class);
    }

    public boolean hasHasGasEmission.id() {
		return !getHasGasEmission.id().isEmpty();
    }

    public void addHasGasEmission.id(Integer newHasGasEmission.id) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASGASEMISSION.ID, newHasGasEmission.id);
    }

    public void removeHasGasEmission.id(Integer oldHasGasEmission.id) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASGASEMISSION.ID, oldHasGasEmission.id);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasGasEmmission.Value
     */
     
    public Collection<? extends Object> getHasGasEmmission.Value() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASGASEMMISSION.VALUE, Object.class);
    }

    public boolean hasHasGasEmmission.Value() {
		return !getHasGasEmmission.Value().isEmpty();
    }

    public void addHasGasEmmission.Value(Object newHasGasEmmission.Value) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASGASEMMISSION.VALUE, newHasGasEmmission.Value);
    }

    public void removeHasGasEmmission.Value(Object oldHasGasEmmission.Value) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASGASEMMISSION.VALUE, oldHasGasEmmission.Value);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasLocation
     */
     
    public Collection<? extends Object> getHasLocation() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLOCATION, Object.class);
    }

    public boolean hasHasLocation() {
		return !getHasLocation().isEmpty();
    }

    public void addHasLocation(Object newHasLocation) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLOCATION, newHasLocation);
    }

    public void removeHasLocation(Object oldHasLocation) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLOCATION, oldHasLocation);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasTime
     */
     
    public Collection<? extends Object> getHasTime() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTIME, Object.class);
    }

    public boolean hasHasTime() {
		return !getHasTime().isEmpty();
    }

    public void addHasTime(Object newHasTime) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTIME, newHasTime);
    }

    public void removeHasTime(Object oldHasTime) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTIME, oldHasTime);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasTrafficVolume.IntersectionStreet
     */
     
    public Collection<? extends String> getHasTrafficVolume.IntersectionStreet() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.INTERSECTIONSTREET, String.class);
    }

    public boolean hasHasTrafficVolume.IntersectionStreet() {
		return !getHasTrafficVolume.IntersectionStreet().isEmpty();
    }

    public void addHasTrafficVolume.IntersectionStreet(String newHasTrafficVolume.IntersectionStreet) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.INTERSECTIONSTREET, newHasTrafficVolume.IntersectionStreet);
    }

    public void removeHasTrafficVolume.IntersectionStreet(String oldHasTrafficVolume.IntersectionStreet) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.INTERSECTIONSTREET, oldHasTrafficVolume.IntersectionStreet);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasTrafficVolume.PrimaryStreet
     */
     
    public Collection<? extends String> getHasTrafficVolume.PrimaryStreet() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.PRIMARYSTREET, String.class);
    }

    public boolean hasHasTrafficVolume.PrimaryStreet() {
		return !getHasTrafficVolume.PrimaryStreet().isEmpty();
    }

    public void addHasTrafficVolume.PrimaryStreet(String newHasTrafficVolume.PrimaryStreet) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.PRIMARYSTREET, newHasTrafficVolume.PrimaryStreet);
    }

    public void removeHasTrafficVolume.PrimaryStreet(String oldHasTrafficVolume.PrimaryStreet) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.PRIMARYSTREET, oldHasTrafficVolume.PrimaryStreet);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasTrafficVolume.Volume
     */
     
    public Collection<? extends Integer> getHasTrafficVolume.Volume() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.VOLUME, Integer.class);
    }

    public boolean hasHasTrafficVolume.Volume() {
		return !getHasTrafficVolume.Volume().isEmpty();
    }

    public void addHasTrafficVolume.Volume(Integer newHasTrafficVolume.Volume) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.VOLUME, newHasTrafficVolume.Volume);
    }

    public void removeHasTrafficVolume.Volume(Integer oldHasTrafficVolume.Volume) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.VOLUME, oldHasTrafficVolume.Volume);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasTrafficVolume.id
     */
     
    public Collection<? extends Integer> getHasTrafficVolume.id() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.ID, Integer.class);
    }

    public boolean hasHasTrafficVolume.id() {
		return !getHasTrafficVolume.id().isEmpty();
    }

    public void addHasTrafficVolume.id(Integer newHasTrafficVolume.id) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.ID, newHasTrafficVolume.id);
    }

    public void removeHasTrafficVolume.id(Integer oldHasTrafficVolume.id) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASTRAFFICVOLUME.ID, oldHasTrafficVolume.id);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasUnit
     */
     
    public Collection<? extends Object> getHasUnit() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNIT, Object.class);
    }

    public boolean hasHasUnit() {
		return !getHasUnit().isEmpty();
    }

    public void addHasUnit(Object newHasUnit) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNIT, newHasUnit);
    }

    public void removeHasUnit(Object oldHasUnit) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUNIT, oldHasUnit);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasValue
     */
     
    public Collection<? extends Object> getHasValue() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASVALUE, Object.class);
    }

    public boolean hasHasValue() {
		return !getHasValue().isEmpty();
    }

    public void addHasValue(Object newHasValue) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASVALUE, newHasValue);
    }

    public void removeHasValue(Object oldHasValue) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASVALUE, oldHasValue);
    }


    /* ***************************************************
     * Data Property http://anonymous.org/resource/fpFreighPerformanceMetrics.owl#hasWeatherConditionID.ID
     */
     
    public Collection<? extends String> getHasWeatherConditionID.ID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASWEATHERCONDITIONID.ID, String.class);
    }

    public boolean hasHasWeatherConditionID.ID() {
		return !getHasWeatherConditionID.ID().isEmpty();
    }

    public void addHasWeatherConditionID.ID(String newHasWeatherConditionID.ID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASWEATHERCONDITIONID.ID, newHasWeatherConditionID.ID);
    }

    public void removeHasWeatherConditionID.ID(String oldHasWeatherConditionID.ID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASWEATHERCONDITIONID.ID, oldHasWeatherConditionID.ID);
    }


}
