package Protege;

import Protege.impl.*;


import java.util.Collection;

import org.protege.owl.codegeneration.CodeGenerationFactory;
import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.FactoryHelper;
import org.protege.owl.codegeneration.impl.ProtegeJavaMapping;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.protege.owl.codegeneration.inference.SimpleInference;

import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;

/**
 * A class that serves as the entry point to the generated code providing access
 * to existing individuals in the ontology and the ability to create new individuals in the ontology.<p>
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: MyFactory<br>
 * @version generated on Thu Nov 16 09:04:53 MST 2017 by danielmejia
 */
public class MyFactory implements CodeGenerationFactory {
    private OWLOntology ontology;
    private ProtegeJavaMapping javaMapping = new ProtegeJavaMapping();
    private FactoryHelper delegate;
    private CodeGenerationInference inference;

    public MyFactory(OWLOntology ontology) {
	    this(ontology, new SimpleInference(ontology));
    }
    
    public MyFactory(OWLOntology ontology, CodeGenerationInference inference) {
        this.ontology = ontology;
        this.inference = inference;
        javaMapping.initialize(ontology, inference);
        delegate = new FactoryHelper(ontology, inference);
    }

    public OWLOntology getOwlOntology() {
        return ontology;
    }
    
    public void saveOwlOntology() throws OWLOntologyStorageException {
        ontology.getOWLOntologyManager().saveOntology(ontology);
    }
    
    public void flushOwlReasoner() {
        delegate.flushOwlReasoner();
    }
    
    public boolean canAs(WrappedIndividual resource, Class<? extends WrappedIndividual> javaInterface) {
    	return javaMapping.canAs(resource, javaInterface);
    }
    
    public  <X extends WrappedIndividual> X as(WrappedIndividual resource, Class<? extends X> javaInterface) {
    	return javaMapping.as(resource, javaInterface);
    }
    
    public Class<?> getJavaInterfaceFromOwlClass(OWLClass cls) {
        return javaMapping.getJavaInterfaceFromOwlClass(cls);
    }
    
    public OWLClass getOwlClassFromJavaInterface(Class<?> javaInterface) {
	    return javaMapping.getOwlClassFromJavaInterface(javaInterface);
    }
    
    public CodeGenerationInference getInference() {
        return inference;
    }

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/smart-cities/Mobility#External
     */

    {
        javaMapping.add("http://ontology.cybershare.utep.edu/smart-cities/Mobility#External", External.class, DefaultExternal.class);
    }

    /**
     * Creates an instance of type External.  Modifies the underlying ontology.
     */
    public External createExternal(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_EXTERNAL, DefaultExternal.class);
    }

    /**
     * Gets an instance of type External with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public External getExternal(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_EXTERNAL, DefaultExternal.class);
    }

    /**
     * Gets all instances of External from the ontology.
     */
    public Collection<? extends External> getAllExternalInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_EXTERNAL, DefaultExternal.class);
    }


    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/smart-cities/Mobility#Incident
     */

    {
        javaMapping.add("http://ontology.cybershare.utep.edu/smart-cities/Mobility#Incident", Incident.class, DefaultIncident.class);
    }

    /**
     * Creates an instance of type Incident.  Modifies the underlying ontology.
     */
    public Incident createIncident(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_INCIDENT, DefaultIncident.class);
    }

    /**
     * Gets an instance of type Incident with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Incident getIncident(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_INCIDENT, DefaultIncident.class);
    }

    /**
     * Gets all instances of Incident from the ontology.
     */
    public Collection<? extends Incident> getAllIncidentInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_INCIDENT, DefaultIncident.class);
    }


    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/smart-cities/Mobility#Occupant
     */

    {
        javaMapping.add("http://ontology.cybershare.utep.edu/smart-cities/Mobility#Occupant", Occupant.class, DefaultOccupant.class);
    }

    /**
     * Creates an instance of type Occupant.  Modifies the underlying ontology.
     */
    public Occupant createOccupant(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_OCCUPANT, DefaultOccupant.class);
    }

    /**
     * Gets an instance of type Occupant with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Occupant getOccupant(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_OCCUPANT, DefaultOccupant.class);
    }

    /**
     * Gets all instances of Occupant from the ontology.
     */
    public Collection<? extends Occupant> getAllOccupantInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_OCCUPANT, DefaultOccupant.class);
    }


    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/smart-cities/Mobility#Person
     */

    {
        javaMapping.add("http://ontology.cybershare.utep.edu/smart-cities/Mobility#Person", Person.class, DefaultPerson.class);
    }

    /**
     * Creates an instance of type Person.  Modifies the underlying ontology.
     */
    public Person createPerson(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_PERSON, DefaultPerson.class);
    }

    /**
     * Gets an instance of type Person with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Person getPerson(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_PERSON, DefaultPerson.class);
    }

    /**
     * Gets all instances of Person from the ontology.
     */
    public Collection<? extends Person> getAllPersonInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_PERSON, DefaultPerson.class);
    }


}
