package Protege;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Thu Nov 16 09:04:53 MST 2017 by danielmejia
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/smart-cities/Mobility#External
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXTERNAL.<p>
     * 
     */
    public static final OWLClass CLASS_EXTERNAL = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#External"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/smart-cities/Mobility#Incident
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INCIDENT.<p>
     * 
     */
    public static final OWLClass CLASS_INCIDENT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#Incident"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/smart-cities/Mobility#Occupant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OCCUPANT.<p>
     * 
     */
    public static final OWLClass CLASS_OCCUPANT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#Occupant"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/smart-cities/Mobility#Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#Person"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#contains
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINS = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#contains"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#has
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#has"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#involves
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVOLVES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVOLVES = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#involves"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#has1000DollarDamage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS1000DOLLARDAMAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS1000DOLLARDAMAGE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#has1000DollarDamage"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasAge
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASAGE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasAge"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasAlcohol
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASALCOHOL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASALCOHOL = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasAlcohol"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasAlcoholBloodContent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASALCOHOLBLOODCONTENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASALCOHOLBLOODCONTENT = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasAlcoholBloodContent"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasAlcoholResult
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASALCOHOLRESULT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASALCOHOLRESULT = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasAlcoholResult"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasAlcoholSpecimanType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASALCOHOLSPECIMANTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASALCOHOLSPECIMANTYPE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasAlcoholSpecimanType"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCMVFlag
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCMVFLAG.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCMVFLAG = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCMVFlag"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCITY = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCity"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCollisionType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCOLLISIONTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCOLLISIONTYPE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCollisionType"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasConstructionWorkerFlag
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONSTRUCTIONWORKERFLAG.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONSTRUCTIONWORKERFLAG = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasConstructionWorkerFlag"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasConstructionZoneFlag
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONSTRUCTIONZONEFLAG.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONSTRUCTIONZONEFLAG = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasConstructionZoneFlag"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCounty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCOUNTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCOUNTY = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCounty"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCRASHID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCRASHID = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashID"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashSeverity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCRASHSEVERITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCRASHSEVERITY = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashSeverity"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCRASHTIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCRASHTIME = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashTime"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashYear
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCRASHYEAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCRASHYEAR = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasCrashYear"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasDayOfWeek
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDAYOFWEEK.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDAYOFWEEK = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasDayOfWeek"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasDeathCount
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDEATHCOUNT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDEATHCOUNT = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasDeathCount"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasDeployedAirbag
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDEPLOYEDAIRBAG.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDEPLOYEDAIRBAG = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasDeployedAirbag"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasGender
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASGENDER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASGENDER = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasGender"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasHWNumber
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASHWNUMBER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASHWNUMBER = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasHWNumber"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasHWSystem
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASHWSYSTEM.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASHWSYSTEM = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasHWSystem"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasHelmet
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASHELMET.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASHELMET = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasHelmet"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasInjury
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINJURY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINJURY = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasInjury"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasInjurySeverity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINJURYSEVERITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINJURYSEVERITY = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasInjurySeverity"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasIntersectionFlag
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINTERSECTIONFLAG.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINTERSECTIONFLAG = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasIntersectionFlag"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasLatitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLATITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLATITUDE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasLatitude"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasLightCondition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLIGHTCONDITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLIGHTCONDITION = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasLightCondition"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasLongitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLONGITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLONGITUDE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasLongitude"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasRRFlag
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASRRFLAG.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASRRFLAG = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasRRFlag"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasRestraintType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASRESTRAINTTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASRESTRAINTTYPE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasRestraintType"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSchoolBusFlag
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSCHOOLBUSFLAG.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSCHOOLBUSFLAG = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSchoolBusFlag"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSchoolZoneFlag
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSCHOOLZONEFLAG.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSCHOOLZONEFLAG = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSchoolZoneFlag"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSpeedLimit
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSPEEDLIMIT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSPEEDLIMIT = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSpeedLimit"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSurfaceCondition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSURFACECONDITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSURFACECONDITION = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasSurfaceCondition"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasWeather
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASWEATHER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASWEATHER = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#hasWeather"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/smart-cities/Mobility#isPersonType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISPERSONTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISPERSONTYPE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/smart-cities/Mobility#isPersonType"));


}
